### ISSUE TITLE
✨ Receive Script: 2 New Functions

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-blender#114]
## Description
There is a function called Receive Script in the Blender connector. But currently it only operates on the received geometry. So all the data contained in the Speckle objects are lost. Considering users can create workflows using that “Data”, 2️⃣ more functions similar to current `execute` function is needed👇:

1. `execute_for_object(scene, object, base)`
    - With this method, desired operation can be performed after each object is received and base object data will be referenced too.
2. `execute_for_all(scene, objects)`
    - With this method, the desired operation can be performed after all objects are received.

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/192831816-1185c18d-ae6c-4f12-830d-1e3582ff943a.png)

@JR-Morgan feel free to add anything you want.

**Comment by tsvilans** [comment]
Hi @bimgeek 

Originally, the script injection operated directly on the base object being received from the stream in order to have access to the full Speckle object and properties. I see now that this is first run through the normal `base_to_native` conversion, which means the function can therefore only operate on the resulting Blender object, as you describe.

I am not sure about the reason for the change, however perhaps the order of conversion (script injection _before_ native conversion) could be changed to solve this.

**Comment by bimgeek** [comment]
Hey @tsvilans 👋,

This issue is related to this [thread ](https://speckle.community/t/get-window-dimensions-in-blender/3309/5)on community. A user wants to add some parameters from BIM model as custom properties in Blender.

> however perhaps the order of conversion (script injection before native conversion) could be changed to solve this.

Thanks for your suggestion!
