### ISSUE TITLE
user information not being retreived from local configuration in Linux

### ISSUE THREAD

**Issue by cristobaltapia** [specklesystems/speckle-blender#165]
Hi, thanks for this plugin for speckle. I am trying to use this under Linux. I read the instructions posted [here](https://github.com/specklesystems/speckle-blender/issues/93#issuecomment-1124250827) but I am getting the following error:

```
Python: Traceback (most recent call last):
  File "/home/tapiac/.config/blender/3.5/scripts/addons/bpy_speckle/operators/users.py", line 82, in execute
    speckle.active_user = str(active_user_index)
TypeError: bpy_struct: item.attr = val: enum "0" not found in ()
```

### Expected vs. Actual Behavior

The users shuold be shown in the GUI, however, an error is raised.

### Reproduction Steps & System Config (win, osx, web, etc.)

- OS: Linux (Ubuntu 22.04)
- Blender: 3.5 (snap package)

The plugin is installed under `~/.confg/blender/3.5/scripts/addons/bpy_speckle`

I have manually added the configuration file under `~/.local/share/Speckle/Accounts` and symlinked `Speckle/` to `~/.config/blender/data/Speckle`.

```sh
❯ ls -lh .config/blender/data 
total 0
lrwxrwxrwx 1 tapiac tapiac 33 Mai 30 11:36 Speckle -> /home/tapiac/.local/share/Speckle
```

In the folder `Accounts` I have placed a json file accoriding to the instructions from [here](https://speckle.guide/user/manager.html#adding-accounts-manually).

Running the following commands in the REPL of Blender returns no account:

```python
>>> import bpy_speckle as speckle
>>> speckle.users.get_local_accounts()
[]
```

**Comment by gjedlicska** [comment]
Hey @cristobaltapia,

thanks for the test. It does makes sense. Speckle uses a centralized config folder under `XDG_CONFIG_HOME` which in most cases is `~/.config/Speckle/`.

Turns out the blender snap is using `classic` confinement to allow full access to the host os file system ( if i remember snap terms correctly ). Another variation case in behavior under linux. ( Hence the lack of official support from us for now )
I'm glad it works for you. 
Do stop by our forum for a bit of show and tell, we're always curious what ppl are doing with Speckle especially if its pushing the boundaries of our mainstream workflows.
