### ISSUE TITLE
🎥 Support for animations

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-blender#37]
This was requested by Jedd Morgan in the last community standup. Sounds fun - needs a bit of scoping on what is important to users and how to structure this data.

**Comment by tsvilans** [comment]
Related to the question about transforms, since you wouldn't want to upload all object data for every single frame. The way external renderers do this is the same: files for object geometry, and separate files with the animation data for the transforms (or complete object data if the object is deforming).

**Comment by JR-Morgan** [comment]
Closing for now, since it's not on our current roadmap
