### ISSUE TITLE
Cylinder geometries are missing caps

### ISSUE THREAD

**Issue by gouldingken** [specklesystems/speckle-blender#62]
Create cylinder mesh in blender.
Export stream to Speckle.
View Stream in web viewer.

Caps (circular ends of cylinder) are missing in viewer. This appears to be a backface issue.

**Comment by tsvilans** [comment]
It sounds like an n-gons issue. Can you use a triangulated cap and see if it is the same issue?

**Comment by gouldingken** [comment]
I'm not much of a blender user, so not really sure how do that. But would that explain the backface normals issue? If I turn on double-sided materials in my own three.js it looks ok.

**Comment by gouldingken** [comment]
actually on closer inspection, that doesn't resolve the caps, it solved an issue with the backfaces for the sides so it looked "capped" but with the correct materials, the caps actually look like they're not there at all.

**Comment by JR-Morgan** [comment]
This issue should be mostly fixed now (by #66) and is included in the latest 2.2.4 version of the blender connector.
End caps still won't show in the viewer just yet (Something we will hopefully fix soon) see https://github.com/specklesystems/speckle-server/issues/444
But you should be able to receive them in Revit, Rhino, Blender, Sketchup, Unreal.
We are still working on supporing n-gons in Unity, AutoCAD, and the Viewer.

If @izzylys agrees, then we can close this issue since it's no longer a problem with speckle-blender

**Comment by izzylys** [comment]
Yep, agreed that this should no longer be an issue after #66 and can be closed.

@gouldingken please let us know if you are still having problems after upgrading to v2.2.4 and we can have a look!
