### ISSUE TITLE
Failed to load ujson for SpeckleBlender on Linux

### ISSUE THREAD

**Issue by cvillagrasa** [specklesystems/speckle-blender#93]
Hi! I've installed SpeckleBlender on Linux, hence without the Speckle Manager magic, by following [these instructions](https://speckle.community/t/blender-no-module-named-specklepy/1320/2), and it was throwing a `ModuleNotFoundError` for `ujson` when activating the add-on within Blender.

For some odd reason, `poetry` does not create a plain "ujson" directory, as it does for the rest of dependencies. I've solved it by simply placing a symbolic link:
`ln -s ./ujson-4.3.0.dist-info ./ujson`

No idea what the underlying reason is, though! I just leave it here for reference in case it helps.

**Comment by cvillagrasa** [comment]
Ok... now what happens, from what I can see, is that `specklepy.api.credentials.get_local_accounts()` does not find any local user database due to the absence of Speckle Manager.

![imagen](https://user-images.githubusercontent.com/57069798/167545799-724cfe42-f35a-493d-9d83-3117512c7a23.png)

I think I'm just going to reboot on Windows for now! 😉

**Comment by gjedlicska** [comment]
hey @cvillagrasa 

sorry for the late response.

here are the steps we took to hack Speckle Blender together for Blender on Linux installed via flatpak:

* find the version number of python that is used by the current blender install, for Blender 3.1 its Python 3.10.2
* create a new virtual env with a matchin python version, and install the requirements of bpy_speckle into that env
* get the user specific folder for the type of installation that was used, for Flatpak its in: ~/.var/app/org.blender.Blender
* to install the speckle addon copy (  or symlink ):
   * the bpy-speckle folder to the addons folder, so that this exists: ${blender_user_config_dir}/config/blender/${blender_version}/scripts/addons/bpy_speckle
  * the site-packages directory of the bpy_speckle dependecies under the name modules so that the ${blender_user_config_dir}/config/blender/${blender_version}/scripts/addons/modules directory exists, and its content is the dependencies of bpy_speckle
* symlink the ~/.local/Speckle folder into ${blender_user_config_dir}/data/ so that the  ${blender_user_config_dir}/data/Speckle folder exists. This way the machine wide accounts and objects cache is used even in a sandbox installed blender
i think this is it

This is a bit more involed and depends on a few factors, but the steps can be adapted to other setups.
Hope this helps

**Comment by JR-Morgan** [comment]
Should be fixed now we are installing platform-speciifc dependencies upon first initialisation
